# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('level', models.CharField(max_length=200)),
                ('instructor_type', models.CharField(max_length=200)),
                ('facility_quality', models.CharField(max_length=200)),
                ('overall_rating', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created date')),
                ('updated', models.DateTimeField(verbose_name='updated date')),
            ],
        ),
        migrations.CreateModel(
            name='Facebookfriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=200)),
                ('friend_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Instructorentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=2200)),
                ('headshot', models.FileField(upload_to='InstructorEntry/headshot/%Y/%m/%d')),
                ('created', models.DateTimeField(verbose_name='created date')),
                ('updated', models.DateTimeField(verbose_name='updated date')),
            ],
        ),
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2200)),
                ('link', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Studioentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classpass_id', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=models.CharField(max_length=200), max_length=255, unique=True)),
                ('description', models.TextField(max_length=2200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('studio_picture', models.FileField(upload_to='StudioEntry/studio_picture/%Y/%m/%d')),
                ('updated', models.DateTimeField(verbose_name='updated date')),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Usercheckin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Userclasstrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usercontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2200)),
                ('link', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created date')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Userfavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=200)),
                ('entity_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('admin_status', models.CharField(max_length=200)),
                ('profile_visible_to', models.CharField(max_length=200)),
                ('allow_followers', models.CharField(max_length=200)),
                ('profile_picture', models.FileField(upload_to='UserProfile/profile_picture/%Y/%m/%d')),
                ('updated', models.DateTimeField(verbose_name='updated date')),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Userreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2200)),
                ('rating', models.CharField(max_length=200)),
                ('entity_type', models.CharField(max_length=200)),
                ('entity_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Usertag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=200)),
                ('entity_id', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
    ]
