# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_auto_20160329_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 15, 43, 29, 986982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studioentry',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 15, 43, 29, 986775, tzinfo=utc)),
        ),
    ]
