# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_auto_20160331_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 17, 29, 32, 385823, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studioentry',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 17, 29, 32, 385598, tzinfo=utc)),
        ),
    ]
