# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0009_auto_20160331_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 4, 17, 15, 25, 959581, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studioentry',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 4, 17, 15, 25, 959330, tzinfo=utc)),
        ),
    ]
