# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_auto_20160404_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 4, 18, 11, 20, 682231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studioentry',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 4, 18, 11, 20, 681855, tzinfo=utc)),
        ),
    ]
