# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0015_auto_20160404_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioentry',
            name='username',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='studioentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 4, 20, 31, 36, 823534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studioentry',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 4, 20, 31, 36, 823318, tzinfo=utc)),
        ),
    ]
